In [1]:
from scipy.io import loadmat

In [2]:
sub_1_20160518 = loadmat('D://PracticumProject1//Data//SEED_IV//eeg-feature-smooth//1//1//1_20160518.mat')
1_20160518

In [3]:
type(sub_1_20160518)

dict

In [4]:
sub_1_20160518.keys()

dict_keys(['__header__', '__version__', '__globals__', 'de_movingAve1', 'de_LDS1', 'psd_movingAve1', 'psd_LDS1', 'de_movingAve2', 'de_LDS2', 'psd_movingAve2', 'psd_LDS2', 'de_movingAve3', 'de_LDS3', 'psd_movingAve3', 'psd_LDS3', 'de_movingAve4', 'de_LDS4', 'psd_movingAve4', 'psd_LDS4', 'de_movingAve5', 'de_LDS5', 'psd_movingAve5', 'psd_LDS5', 'de_movingAve6', 'de_LDS6', 'psd_movingAve6', 'psd_LDS6', 'de_movingAve7', 'de_LDS7', 'psd_movingAve7', 'psd_LDS7', 'de_movingAve8', 'de_LDS8', 'psd_movingAve8', 'psd_LDS8', 'de_movingAve9', 'de_LDS9', 'psd_movingAve9', 'psd_LDS9', 'de_movingAve10', 'de_LDS10', 'psd_movingAve10', 'psd_LDS10', 'de_movingAve11', 'de_LDS11', 'psd_movingAve11', 'psd_LDS11', 'de_movingAve12', 'de_LDS12', 'psd_movingAve12', 'psd_LDS12', 'de_movingAve13', 'de_LDS13', 'psd_movingAve13', 'psd_LDS13', 'de_movingAve14', 'de_LDS14', 'psd_movingAve14', 'psd_LDS14', 'de_movingAve15', 'de_LDS15', 'psd_movingAve15', 'psd_LDS15', 'de_movingAve16', 'de_LDS16', 'psd_movingAve16', 'p

In [16]:
type(sub_1_20160518['de_movingAve3']),sub_1_20160518['de_movingAve3'].shape

(numpy.ndarray, (62, 49, 5))

In [6]:
type(sub_1_20160518['de_movingAve1'][0][0]),sub_1_20160518['de_movingAve1'][0][0].shape

(numpy.ndarray, (5,))

In [16]:
sub_1_20160518['de_movingAve1'][0][0]

array([27.77101647, 24.87116042, 23.30638606, 21.91870888, 20.26050386])

In [20]:
sub_1_20160518['de_movingAve1'][61][41]

array([24.38006719, 23.23814819, 22.72210432, 21.60296696, 18.668718  ])

In [10]:
type(sub_1_20160518['de_LDS7']),sub_1_20160518['de_LDS7'].shape

(numpy.ndarray, (62, 38, 5))

In [11]:
type(sub_1_20160518['de_LDS11']),sub_1_20160518['de_LDS11'].shape

(numpy.ndarray, (62, 12, 5))

In [9]:
type(sub_1_20160518['psd_LDS24']),sub_1_20160518['psd_LDS24'].shape

(numpy.ndarray, (62, 34, 5))

In [10]:
eye_1_20160518 = loadmat('D://PracticumProject1//Data//SEED_IV//EYE-FEATURE-SMOOTH//1//1//1_20160518.mat')

In [11]:
eye_1_20160518.keys()

dict_keys(['__header__', '__version__', '__globals__', 'eye_1', 'eye_2', 'eye_3', 'eye_4', 'eye_5', 'eye_6', 'eye_7', 'eye_8', 'eye_9', 'eye_10', 'eye_11', 'eye_12', 'eye_13', 'eye_14', 'eye_15', 'eye_16', 'eye_17', 'eye_18', 'eye_19', 'eye_20', 'eye_21', 'eye_22', 'eye_23', 'eye_24'])

In [12]:
type(eye_1_20160518['eye_1']),eye_1_20160518['eye_1'].shape

(numpy.ndarray, (31, 42))

In [13]:
eye_1_20160518['eye_1'][3][:]

array([7.3329878 , 7.33169364, 7.33088049, 7.33201392, 7.33245532,
       7.33405857, 7.33364459, 7.33687374, 7.33893538, 7.33698595,
       7.33513466, 7.3283525 , 7.32320744, 7.31828965, 7.31514636,
       7.3138069 , 7.30881294, 7.30530013, 7.29717018, 7.28841175,
       7.2815848 , 7.27483154, 7.26865786, 7.26284461, 7.25753162,
       7.25527774, 7.25758919, 7.25716992, 7.25518039, 7.25165786,
       7.25244932, 7.25541254, 7.25881599, 7.26317333, 7.26338326,
       7.26364136, 7.26766102, 7.27330158, 7.27637904, 7.28098156,
       7.28484813, 7.29266592])

In [33]:
eeg_raw_1_20160518 = loadmat('D://PracticumProject1//Data//SEED_IV//eeg-raw-data//1//1_20160518.mat')

In [34]:
eeg_raw_1_20160518.keys()

dict_keys(['__header__', '__version__', '__globals__', 'cz_eeg1', 'cz_eeg2', 'cz_eeg3', 'cz_eeg4', 'cz_eeg5', 'cz_eeg6', 'cz_eeg7', 'cz_eeg8', 'cz_eeg9', 'cz_eeg10', 'cz_eeg11', 'cz_eeg12', 'cz_eeg13', 'cz_eeg14', 'cz_eeg15', 'cz_eeg16', 'cz_eeg17', 'cz_eeg18', 'cz_eeg19', 'cz_eeg20', 'cz_eeg21', 'cz_eeg22', 'cz_eeg23', 'cz_eeg24'])

In [35]:
type(eeg_raw_1_20160518['cz_eeg1']),eeg_raw_1_20160518['cz_eeg1'].shape

(numpy.ndarray, (62, 33601))

In [45]:
eeg_raw_1_20160518['cz_eeg1'][61][1:5]

array([33.25939178, 39.78610039, 50.81295967, 51.34940147])

In [7]:
eye_sub_1_20160518 = loadmat('D://PracticumProject1//Data//SEED_IV//EYE-FEATURE-SMOOTH//1//1//1_20160518.mat')

In [8]:
eye_sub_1_20160518C

dict_keys(['__header__', '__version__', '__globals__', 'eye_1', 'eye_2', 'eye_3', 'eye_4', 'eye_5', 'eye_6', 'eye_7', 'eye_8', 'eye_9', 'eye_10', 'eye_11', 'eye_12', 'eye_13', 'eye_14', 'eye_15', 'eye_16', 'eye_17', 'eye_18', 'eye_19', 'eye_20', 'eye_21', 'eye_22', 'eye_23', 'eye_24'])

In [20]:
eye_raw_sub_1_20160518 = loadmat('D://PracticumProject1//Data//SEED_IV//EYE-RAW-DATA//eye_raw_data//1_20160518_blink.mat')

In [22]:
eye_raw_sub_1_20160518.keys()

dict_keys(['__header__', '__version__', '__globals__', 'Eye_Blink'])

In [26]:
eye_raw_sub_1_20160518['Eye_Blink'].shape

(24, 1)

In [27]:
type(eye_raw_sub_1_20160518['Eye_Blink'])

numpy.ndarray

In [32]:
eye_raw_sub_1_20160518['Eye_Blink'].dtype

dtype('O')

In [33]:
type(eye_raw_sub_1_20160518)

dict

In [37]:
eye_raw_sub_1_20160518['Eye_Blink'][1][0]

array([[466],
       [366],
       [332],
       [366],
       [532],
       [232],
       [299],
       [365],
       [765],
       [299],
       [298],
       [432],
       [765],
       [299],
       [299],
       [299],
       [332],
       [667],
       [299],
       [300],
       [299],
       [465],
       [366],
       [404],
       [432],
       [399],
       [333],
       [299],
       [299],
       [465],
       [399],
       [498],
       [632],
       [332],
       [334],
       [299],
       [366],
       [399],
       [132],
       [366],
       [332],
       [366],
       [199],
       [299],
       [366],
       [332],
       [398],
       [698],
       [332],
       [432],
       [432],
       [598],
       [363],
       [333]], dtype=uint16)