In [49]:
import cv2
import numpy as np

import matplotlib.pyplot as plt
#import ffmpeg

In [11]:
import os
os. chdir("C:/DeapVideoData/face_video/s01")

In [24]:
os. getcwd() 

'C:\\DeapVideoData\\face_video\\s01'

In [3]:
cap= cv2.VideoCapture("C:\\DeapVideoData\\face_video\\s01\\s01_trial01.avi")

In [17]:
type(s01_video)

cv2.VideoCapture

In [57]:

cap = cv2.VideoCapture(r"C:\\DeapVideoData\\face_video\\s01\\s01_trial01.avi")
counter = 0
while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Display the resulting frame
    if (ret != True):
        break
    cv2.imshow('Video', frame)
    
    print("Frame number: " + str(counter))
    counter = counter+1
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

Frame number: 0
Frame number: 1
Frame number: 2
Frame number: 3
Frame number: 4
Frame number: 5
Frame number: 6
Frame number: 7
Frame number: 8
Frame number: 9
Frame number: 10
Frame number: 11
Frame number: 12
Frame number: 13
Frame number: 14
Frame number: 15
Frame number: 16
Frame number: 17
Frame number: 18
Frame number: 19
Frame number: 20
Frame number: 21
Frame number: 22
Frame number: 23
Frame number: 24
Frame number: 25
Frame number: 26
Frame number: 27
Frame number: 28
Frame number: 29
Frame number: 30
Frame number: 31
Frame number: 32
Frame number: 33
Frame number: 34
Frame number: 35
Frame number: 36
Frame number: 37
Frame number: 38
Frame number: 39
Frame number: 40
Frame number: 41
Frame number: 42
Frame number: 43
Frame number: 44
Frame number: 45
Frame number: 46
Frame number: 47
Frame number: 48
Frame number: 49
Frame number: 50
Frame number: 51
Frame number: 52
Frame number: 53
Frame number: 54
Frame number: 55
Frame number: 56
Frame number: 57
Frame number: 58
Frame n

Frame number: 461
Frame number: 462
Frame number: 463
Frame number: 464
Frame number: 465
Frame number: 466
Frame number: 467
Frame number: 468
Frame number: 469
Frame number: 470
Frame number: 471
Frame number: 472
Frame number: 473
Frame number: 474
Frame number: 475
Frame number: 476
Frame number: 477
Frame number: 478
Frame number: 479
Frame number: 480
Frame number: 481
Frame number: 482
Frame number: 483
Frame number: 484
Frame number: 485
Frame number: 486
Frame number: 487
Frame number: 488
Frame number: 489
Frame number: 490
Frame number: 491
Frame number: 492
Frame number: 493
Frame number: 494
Frame number: 495
Frame number: 496
Frame number: 497
Frame number: 498
Frame number: 499
Frame number: 500
Frame number: 501
Frame number: 502
Frame number: 503
Frame number: 504
Frame number: 505
Frame number: 506
Frame number: 507
Frame number: 508
Frame number: 509
Frame number: 510
Frame number: 511
Frame number: 512
Frame number: 513
Frame number: 514
Frame number: 515
Frame numb

Frame number: 917
Frame number: 918
Frame number: 919
Frame number: 920
Frame number: 921
Frame number: 922
Frame number: 923
Frame number: 924
Frame number: 925
Frame number: 926
Frame number: 927
Frame number: 928
Frame number: 929
Frame number: 930
Frame number: 931
Frame number: 932
Frame number: 933
Frame number: 934
Frame number: 935
Frame number: 936
Frame number: 937
Frame number: 938
Frame number: 939
Frame number: 940
Frame number: 941
Frame number: 942
Frame number: 943
Frame number: 944
Frame number: 945
Frame number: 946
Frame number: 947
Frame number: 948
Frame number: 949
Frame number: 950
Frame number: 951
Frame number: 952
Frame number: 953
Frame number: 954
Frame number: 955
Frame number: 956
Frame number: 957
Frame number: 958
Frame number: 959
Frame number: 960
Frame number: 961
Frame number: 962
Frame number: 963
Frame number: 964
Frame number: 965
Frame number: 966
Frame number: 967
Frame number: 968
Frame number: 969
Frame number: 970
Frame number: 971
Frame numb

Frame number: 1357
Frame number: 1358
Frame number: 1359
Frame number: 1360
Frame number: 1361
Frame number: 1362
Frame number: 1363
Frame number: 1364
Frame number: 1365
Frame number: 1366
Frame number: 1367
Frame number: 1368
Frame number: 1369
Frame number: 1370
Frame number: 1371
Frame number: 1372
Frame number: 1373
Frame number: 1374
Frame number: 1375
Frame number: 1376
Frame number: 1377
Frame number: 1378
Frame number: 1379
Frame number: 1380
Frame number: 1381
Frame number: 1382
Frame number: 1383
Frame number: 1384
Frame number: 1385
Frame number: 1386
Frame number: 1387
Frame number: 1388
Frame number: 1389
Frame number: 1390
Frame number: 1391
Frame number: 1392
Frame number: 1393
Frame number: 1394
Frame number: 1395
Frame number: 1396
Frame number: 1397
Frame number: 1398
Frame number: 1399
Frame number: 1400
Frame number: 1401
Frame number: 1402
Frame number: 1403
Frame number: 1404
Frame number: 1405
Frame number: 1406
Frame number: 1407
Frame number: 1408
Frame number

Frame number: 1794
Frame number: 1795
Frame number: 1796
Frame number: 1797
Frame number: 1798
Frame number: 1799
Frame number: 1800
Frame number: 1801
Frame number: 1802
Frame number: 1803
Frame number: 1804
Frame number: 1805
Frame number: 1806
Frame number: 1807
Frame number: 1808
Frame number: 1809
Frame number: 1810
Frame number: 1811
Frame number: 1812
Frame number: 1813
Frame number: 1814
Frame number: 1815
Frame number: 1816
Frame number: 1817
Frame number: 1818
Frame number: 1819
Frame number: 1820
Frame number: 1821
Frame number: 1822
Frame number: 1823
Frame number: 1824
Frame number: 1825
Frame number: 1826
Frame number: 1827
Frame number: 1828
Frame number: 1829
Frame number: 1830
Frame number: 1831
Frame number: 1832
Frame number: 1833
Frame number: 1834
Frame number: 1835
Frame number: 1836
Frame number: 1837
Frame number: 1838
Frame number: 1839
Frame number: 1840
Frame number: 1841
Frame number: 1842
Frame number: 1843
Frame number: 1844
Frame number: 1845
Frame number

Frame number: 2237
Frame number: 2238
Frame number: 2239
Frame number: 2240
Frame number: 2241
Frame number: 2242
Frame number: 2243
Frame number: 2244
Frame number: 2245
Frame number: 2246
Frame number: 2247
Frame number: 2248
Frame number: 2249
Frame number: 2250
Frame number: 2251
Frame number: 2252
Frame number: 2253
Frame number: 2254
Frame number: 2255
Frame number: 2256
Frame number: 2257
Frame number: 2258
Frame number: 2259
Frame number: 2260
Frame number: 2261
Frame number: 2262
Frame number: 2263
Frame number: 2264
Frame number: 2265
Frame number: 2266
Frame number: 2267
Frame number: 2268
Frame number: 2269
Frame number: 2270
Frame number: 2271
Frame number: 2272
Frame number: 2273
Frame number: 2274
Frame number: 2275
Frame number: 2276
Frame number: 2277
Frame number: 2278
Frame number: 2279
Frame number: 2280
Frame number: 2281
Frame number: 2282
Frame number: 2283
Frame number: 2284
Frame number: 2285
Frame number: 2286
Frame number: 2287
Frame number: 2288
Frame number

Frame number: 2686
Frame number: 2687
Frame number: 2688
Frame number: 2689
Frame number: 2690
Frame number: 2691
Frame number: 2692
Frame number: 2693
Frame number: 2694
Frame number: 2695
Frame number: 2696
Frame number: 2697
Frame number: 2698
Frame number: 2699
Frame number: 2700
Frame number: 2701
Frame number: 2702
Frame number: 2703
Frame number: 2704
Frame number: 2705
Frame number: 2706
Frame number: 2707
Frame number: 2708
Frame number: 2709
Frame number: 2710
Frame number: 2711
Frame number: 2712
Frame number: 2713
Frame number: 2714
Frame number: 2715
Frame number: 2716
Frame number: 2717
Frame number: 2718
Frame number: 2719
Frame number: 2720
Frame number: 2721
Frame number: 2722
Frame number: 2723
Frame number: 2724
Frame number: 2725
Frame number: 2726
Frame number: 2727
Frame number: 2728
Frame number: 2729
Frame number: 2730
Frame number: 2731
Frame number: 2732
Frame number: 2733
Frame number: 2734
Frame number: 2735
Frame number: 2736
Frame number: 2737
Frame number

In [1]:
from scipy.io import loadmat

In [15]:
df=loadmat('C://Users//tabas//Documents//JupyterNotebook_Python//Deap//matlab//s01.mat')

In [16]:
df.keys()

dict_keys(['__header__', '__version__', '__globals__', 'labels', 'data'])

In [17]:
# 40 channels
# 40 trials per person
# 8064 readings @ 128 hz. That is equivalent to 128 readings per sec for 63 sec
df['data'].shape

(40, 40, 8064)

In [18]:
df['data'][0][0]

array([ 0.94823168,  1.65333533,  3.01372577, ..., -2.82648937,
       -4.47722969, -3.67692812])

In [19]:
df['data'][0][31]

array([0.37227063, 2.07619495, 4.46521875, ..., 2.23958511, 3.18256605,
       4.70807159])

In [21]:
df['labels'].shape

(40, 4)

In [24]:
type(df['labels'])

numpy.ndarray

In [48]:
# Range of values (maximum - minimum) along an axis.
np.ptp(df['labels'],axis=0)

array([7.64, 6.07, 6.96, 4.6 ])

In [46]:
np.nanmax(df['labels'],axis=0)

array([9.  , 8.15, 9.  , 8.47])

In [47]:
np.nanmin(df['labels'],axis=0)

array([1.36, 2.08, 2.04, 3.87])

In [45]:
df['labels'][:,3]

array([7.83, 8.47, 7.08, 8.06, 6.05, 8.03, 7.04, 5.87, 5.99, 7.09, 6.24,
       7.35, 6.18, 5.04, 5.04, 7.14, 6.41, 8.01, 6.79, 8.13, 7.86, 7.37,
       7.9 , 8.22, 7.21, 8.24, 7.29, 7.87, 8.14, 7.33, 8.04, 3.95, 5.13,
       6.92, 5.18, 3.87, 6.77, 6.62, 6.15, 5.97])